// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package jt.chat.grpc;

public interface JoinRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.JoinRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chat.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.chat.User user = 1;</code>
   */
  jt.chat.grpc.User getUser();
  /**
   * <code>.chat.User user = 1;</code>
   */
  jt.chat.grpc.UserOrBuilder getUserOrBuilder();
}
