// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package jt.chat.grpc;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_JoinRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_JoinRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_JoinRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_JoinRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\004chat\"\030\n\004User\022\020\n\010username\030\001" +
      " \001(\t\"+\n\017JoinRoomRequest\022\030\n\004user\030\001 \001(\0132\n." +
      "chat.User\"J\n\020JoinRoomResponse\022\034\n\024is_pass" +
      "word_required\030\001 \001(\010\022\030\n\004user\030\002 \003(\0132\n.chat" +
      ".User2C\n\004Chat\022;\n\010JoinRoom\022\025.chat.JoinRoo" +
      "mRequest\032\026.chat.JoinRoomResponse\"\000B\032\n\014jt" +
      ".chat.grpcB\010ProtocolP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_chat_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_User_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_chat_JoinRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_JoinRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_JoinRoomRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_chat_JoinRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chat_JoinRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_JoinRoomResponse_descriptor,
        new java.lang.String[] { "IsPasswordRequired", "User", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
