// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package jt.chat.grpc;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name as shown to all other users
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * name as shown to all other users
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
